== librealtouch

By Kyle Machulis (qDot) - http://www.nonpolynomial.com

Project Repo: http://www.github.com/qdot/librealtouch

Please report all bugs and feature requests to http://www.github.com/qdot/librealtouch/issues

=== Description

librealtouch is an open source reimplementation of the RealTouch
Platform Agent. There are no functional differences between
librealtouch and the official RealTouch Platform Agent. librealtouch
is provided to access the RealTouch on platforms unsupported by the
company (OS X, linux, etc...)

=== Requirements

For the driver, you'll need

* hidapi - http://www.signal11.us/oss/hidapi/

=== Basic Compiling Instructions

To use CMake:

* Make a directory somewhere. Like, say, 'build' in your repo directory.
* Go into that directory
* Type cmake ..
* Watch the magic happen
* After this, just run make and you'll be fine.
* If you want to use an IDE or whatever, well, you'll figure it out.

=== Command Index

(Shortened version of command index available in CDK Documentation.
CDK is available at http://developer.realtouch.com/downloads.php)

==== General Format

----------
<comment> <statement><newline>
----------

==== Movement (Vector)

----------
V <magnitude> <axis> <direction> <duration> [<inMagnitude> <inDuration> <outMagnitude> <outDuration>]
----------

==== Periodic Movement

----------
P <period> <magnitude> <axis> <direction> <duration> [<inMagnitude> <inDuration> <outMagnitude> <outDuration>]
----------

==== Heat 

----------
H <magnitude>
----------

==== Lube

----------
L <magnitude> <duration>
----------

==== Stop

----------
S <axis>
----------

Axis Values
* "A": "All"—stop every component of the device
* "H": "Heater"—turn off the heater
* "L": "Lube"—stop the dispensing of lube
* "T": "Top Belt"—stop the top belt
* "B": "Bottom Belt"—stop the bottom belt
* "U": "Both Belts"—stop both the top and bottom belt
* "S": "Squeeze" (orifice)—stop the orifice

=== Licensing

----------

Copyright (c) 2007-2012, Kyle Machulis/Nonpolynomial Labs
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Kyle Machulis/Nonpolynomial Labs nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY Kyle Machulis/Nonpolynomial Labs ''AS IS'' AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL Kyle Machulis/Nonpolynomial Labs BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE

----------
